version: "3"
services:
    elasticsearch:
        image: elasticsearch:7.6.2
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elknetwork
    kibana:
        image: kibana:7.6.2
        container_name: kibana
        hostname: kibana
        ports:
            - 5601:5601
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.6.2
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 5044:5044
            - 5000:5000/tcp
            - 5000:5000/udp
        volumes:
          - ./logstash/pipeline:/usr/share/logstash/pipeline/
        links:
            - elasticsearch:elasticsearch
        depends_on:
          - elasticsearch
        networks:
          - elknetwork        
networks:
    elknetwork:
        driver: bridge          